builds:
  - goos:
      - linux
      - windows
      - darwin
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: tar.gz
    format: tar.gz
  - id: binary
    format: binary
