name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: actions/setup-python@v5
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Go Tests
        run: |
          go build -ldflags="-s -w" 
          go test -v
